#!/bin/bash -ex

DOCKER_ARCH=${BUILD_ARCH:-amd64}
DOCKER_ORG=samip537
DOCKER_IMAGE=archlinux:${DOCKER_ARCH}

if [[ -z "${BUILD_ARCH}"] && ${BUILD_ARCH} = "amd64"]; then
	docker build --build-arg ARCH=${DOCKER_ARCH} \
		-t $DOCKER_ORG/$DOCKER_IMAGE \
		-f Dockerfile.amd64 .
else
	docker build --build-arg ARCH=${DOCKER_ARCH} \
  		-t $DOCKER_ORG/$DOCKER_IMAGE \
		-f Dockerfile .

	docker build --build-arg ARCH=${DOCKER_ARCH} \
  		-t $DOCKER_ORG/$DOCKER_IMAGE-devel \
		-f Dockerfile.devel .
fi
