ARG ARCH=amd64
FROM samip537/archlinux:$ARCH-latest

RUN pacman-key --init
RUN pacman-key --populate archlinux || pacman-key --populate archlinuxarm

RUN pacman -Syu --noconfirm --needed base-devel

# Remove current pacman database, likely outdated very soon
RUN rm /var/lib/pacman/sync/*
