ARG ARCH=amd64
FROM samip537/archlinux:$ARCH

RUN pacman-key --init
RUN pacman-key --populate archlinux || pacman-key --populate archlinuxarm

RUN pacman -Syu --noconfirm --needed base-devel git

# Remove current pacman database, likely outdated very soon
RUN rm /var/lib/pacman/sync/* && rm -rf /var/cache/*
