ARG ARCH=amd64
FROM samip537/archlinux:$ARCH

RUN pacman-key --init
RUN pacman-key --populate archlinux || pacman-key --populate archlinuxarm

# Install packaged and remove database/caches and man pages.
RUN pacman -Syu --noconfirm --needed base-devel git && rm -f \
      /var/cache/pacman/pkg/* \
      /var/lib/pacman/sync/* \
      /README \
      /etc/pacman.d/mirrorlist.pacnew
