name: Builder

on:
  push:
    branches: master
  schedule:
    # Run daily
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-arch:
          - amd64
          - arm32v6
          - arm32v7
          - arm64v8
    env:
      BUILD_ARCH: ${{ matrix.build-arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.2
      - name: Build
        run: ./build
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        run: ./push
  create-manifest:
    runs-on: ubuntu-20.04
    needs: build
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create manifest
        run: ./create-manifest
