name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build minimal
        uses: docker/build-push-action@v2.3.0
        with:
         build-args: ARCH=arm32v6 ARCH=arm32v7 ARCH=amd64
         file: Dockerfile
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
         
      - name: Build with devel tools
        uses: docker/build-push-action@v2.3.0
        with:
         file: Dockerfile.devel
         build-args: ARCH=arm32v6 ARCH=arm32v7 ARCH=amd64
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
         
      - name: Build with devel and yay
        uses: docker/build-push-action@v2.3.0
        with:
         file: Dockerfile.devel-yay
         build-args: ARCH=arm32v6 ARCH=arm32v7 ARCH=amd64
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
